### ISSUE TITLE
undefined method `where_values' error is occured

### ISSUE THREAD

**Issue by say8425** [ReneB/activerecord-like#8]
In rails 5 and ruby 2.4.0 `where_values` is undefined.
And I fount [`where_values` is deprecated](https://github.com/DockYard/postgres_ext/issues/180#issuecomment-186170500).

**Comment by ReneB** [comment]
Darn, I was afraid of something like that happening in the near future. Sorry I didn't get around to testing it yet - I'll see what I can do in a couple of days. This project has been relegated to my spare time since I switched jobs and I currently don't actively use it myself, but I'll try to fix this soon!
